# Computing the S isotope fractionation factors for the oxidation of S0 to sulfate by Chlorobaculum tepidum from experimental data

In [1640]:
# For numerical calculations
import numpy as np
import pandas as pd
import scipy as sp
import math
import matplotlib.animation as animation
from scipy.integrate import odeint
from numpy import arange
from pylab import *
from scipy.integrate import odeint
import scipy.optimize 
from scipy.optimize import leastsq
from math import exp
from collections import OrderedDict
from sklearn.linear_model import LinearRegression
pd.options.mode.chained_assignment = None
import git

# Import plotting features
import matplotlib.pyplot as plt
import seaborn as sns

# Find home directory for repo
repo = git.Repo("./", search_parent_directories=True)
homedir = repo.working_dir

# Set plot style
sns.set_style("ticks")
sns.set_palette("colorblind", color_codes=True)
sns.set_context("paper")

# Magic command to plot inline
%matplotlib inline

#To graph in SVG (high def)
%config InlineBackend.figure_format="svg"

In [1641]:
# Import table with data
df_data =  pd.read_csv ('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210427_EA.csv')

#Remove NaN cells
df_data = df_data.dropna(subset=['Identifier'])

# Keep only rows with Peak Nr=3, since Peak Nr=1,2,4 and 5 
# correspond to the reference gas
#Select rows to drop
df_data = df_data[df_data.Peak_Nr == 3]

df_data.head()

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (0,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard

Then, let's load the data for the blanks:

In [1642]:
# Import table with the raw data for blanks
df_blanks = pd.read_csv('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210427_blanks.csv')

# Remove rows with missing data
df_blanks.dropna(how='any', inplace=True)

# Keep only rows with Peak Nr=3
df_blanks = df_blanks[df_blanks.Peak_Nr == 3]
df_blanks.head()

,Identifier,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Date
2,blank,3,1.731,1.650,0.081,55,267,6.968,20210427
7,blank,3,1.579,1.504,0.074,46,225,4.510,20210427
12,blank,3,1.809,1.724,0.085,51,249,3.460,20210427
17,blank,3,1.665,1.588,0.077,49,236,8.438,20210427
22,blank,3,1.675,1.597,0.077,50,239,5.706,20210427

Finally, let's load the data for the linearity test at the beginning of the run:

In [1643]:
# Import file
df_lin =  pd.read_csv('/Users/daniosro/git/MSO/ctep_wt/data/raw/EA/20210427_linearity.csv')
df_lin.head()

  Identifier  Peak_Nr  Ampl_64  Ampl_66   d34S
0  linearity        1     7576    36415  0.000
1  linearity        1      604     2902 -0.147
2  linearity        2     1827     8777  0.000
3  linearity        3     3133    15052  0.080
4  linearity        4     3800    18258  0.084

Now, let's implement the corrections.

## Blank correction

In [1644]:
# Get the average area all for the blanks
blank_area_all_average = df_blanks["Area_All"].mean()

# Get the average d34S for the blanks
blank_d34s_average = df_blanks["d34S"].mean()

# Append a column to the data dataframe with the 
# correction of area by blank: substraction of the
# area of the measurement by the area of the blank

df_data['Correction_of_area_blank'] = \
    np.subtract(df_data['Area_All'], blank_area_all_average)

# Correction of d34S by blank: 
    
# Get the product of the d34S by the area of each measurement
num1 = np.multiply (df_data['d34S'], df_data['Area_All'])
# Get the product of the d34S by the area of the average of the blanks
num2 = blank_d34s_average * blank_area_all_average  
#Subtract the product of d34S by the product of the blanks
num = np.subtract (num1, num2)
#Divide by the area corrected by blank and
#append column to the data dataframe
df_data['Correction_of_d34S_blank'] = \
    np.divide (num, df_data['Correction_of_area_blank'])

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard,30.005667,2.993089

## Linearity correction

In [1645]:
# Create variables for linear regression
# x will be the amplitude of the peak of mass 64 = ^32S + ^16O + ^16O
# We divided by 1000 to convert volts ot milivolts
x = (df_lin['Ampl_64'].values/1000).reshape((-1,1))
# y will be the values of d34S
y = (df_lin['d34S'])

# Create model of linear regression
model = LinearRegression().fit(x,y)

#Determine R square, intercept and slope
r_sq = model.score(x,y)
intercept = model.intercept_
s = model.coef_
slope=s[0]

# Calculate an amplitude difference by centering around an arbitrary 
# value in the Ampl_64 column of the data dataframe  
num= np.subtract(df_data['Ampl_64'], 800)
ampl_difference = np.divide (num, 1000)

# Calculate the amplitude correction factor
ampl_correction_factor = (slope * ampl_difference)+intercept

# Correct the d34S corrected by amplitude by
# subtracting the blank corrected data by the amplitude correction
# factor and append the column to the data dataframe
df_data['Correction_of_d34S_by_amplitude'] = \
    np.subtract(df_data['Correction_of_d34S_blank'], ampl_correction_factor)

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738,1.479052
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449,1.903875
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892,1.567164
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554,1.662475
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard,30.005667,2.993089,3.091956

## Standard correction

First, let's create a category column in the dataframe according to the size of the area of the peak of each sample and standard.

In [1646]:
# Correct each sample by standards with similar areas

#Create standard correction group empty list
Std_group = []
# Classify the area of the samples by category 
# Loop through dataframe rows
for row in df_data['Area_All']:
    if row <= 45:
        Std_group.append ('low')
    else:
        Std_group.append ('high')
# Append to data dataframe 
df_data['Std_group'] = Std_group
df_data.head()

df_data

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738,1.479052,low
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449,1.903875,high
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892,1.567164,high
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554,1.662475,high
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard,30.005667,2.993089,3.091956,low
27,AGS2,NaN,NaN,3.0,17.677,16.865,0.812,529.0,2537.0,2.962,standard,15.439667,2.577607,2.696199,low
32,AGS2,NaN,NaN,3.0,67.674,64.568,3.106,2080.0,9981.0,1.387,standard,65.436667,1.242453,1.275585,high
37,AGS2,NaN,NaN,3.0,21.169,20.196,0.973,634.0,3045.0,1.978,standard,18.931667,1.548221,1.661027,low
42,AGS2,NaN,NaN,3.0,49.852,47.562,2.289,1446.0,6945.0,1.215,standard,47.614667,1.008267,1.076332,high
47,AGS2,NaN,NaN,3.0,34.895,33.292,1.603,995.0,4779.0,1.457,standard,32.657667,1.172164,1.265079,low
52,b,52.50,7.0,3.0,32.441,31.328,1.112,74.0,355.0,-1.356,sample,30.203667,-1.872351,-1.728689,low
57,b,61.50,4.0,3.0,19.228,18.349,1.880,551.0,2635.0,-1.166,sample,16.990667,-2.058879,-1.941499,low
62,b,61.50,5.0,3.0,30.804,29.389,1.415,949.0,4535.0,-1.123,sample,28.566667,-1.650692,-1.555242,low
67,b,69.00,7.0,3.0,29.659,28.301,1.357,927.0,4429.0,-1.046,sample,27.421667,-1.589444,-1.492781,low
72,b,148.50,5.0,3.0,24.879,23.741,1.139,768.0,3671.0,-1.674,sample,22.641667,-2.394229,-2.288806,low
77,b,163.50,8.0,3.0,55.000,52.486,2.514,1674.0,7999.0,-1.599,sample,52.762667,-1.904886,-1.849384,high
82,b,163.50,9.0,3.0,37.509,35.792,1.717,1059.0,5065.0,-1.892,sample,35.271667,-2.368159,-2.278770,low
87,b,188.00,8.0,3.0,20.581,19.638,0.944,623.0,2978.0,-1.225,sample,18.343667,-2.059218,-1.945805,low
92,b,216.00,9.0,3.0,34.680,33.007,1.673,458.0,2194.0,-1.679,sample,32.442667,-2.181991,-2.059487,low
97,b,244.50,9.0,3.0,39.299,38.873,1.426,295.0,1409.0,-2.063,sample,37.061667,-2.526484,-2.394999,low
102,b,316.50,6.0,3.0,41.001,40.497,1.504,354.0,1692.0,-2.044,sample,38.763667,-2.486037,-2.357803,low
107,b,397.50,4.0,3.0,39.404,37.602,1.802,1186.0,5669.0,-2.005,sample,37.166667,-2.463683,-2.381292,low
112,b,397.50,6.0,3.0,22.477,21.448,1.029,710.0,3392.0,-2.170,sample,20.239667,-3.030533,-2.921914,low
117,b,671.00,9.0,3.0,53.169,50.738,2.431,1557.0,7443.0,-1.805,sample,50.931667,-2.130932,-2.068983,high
122,d,76.00,1.0,3.0,28.908,27.586,1.323,903.0,4312.0,-1.216,sample,26.670667,-1.789007,-1.691022,low
127,d,92.75,1.0,3.0,39.545,38.651,0.894,582.0,2783.0,-1.262,sample,37.307667,-1.674392,-1.558721,low
132,d,92.75,2.0,3.0,39.323,37.523,1.799,1212.0,5795.0,-1.202,sample,37.085667,-1.613241,-1.532282,low
137,d,163.50,1.0,3.0,33.991,32.437,1.554,981.0,4690.0,-1.266,sample,31.753667,-1.750805,-1.657118,low
142,d,163.50,2.0,3.0,35.970,34.324,1.646,1062.0,5080.0,-1.344,sample,33.732667,-1.805536,-1.716313,low
147,d,188.00,2.0,3.0,40.407,39.930,1.477,303.0,1448.0,-1.573,sample,38.169667,-1.994309,-1.863264,low
152,d,188.00,3.0,3.0,45.960,43.861,2.100,1355.0,6472.0,-1.492,sample,43.722667,-1.855655,-1.782576,high
157,d,216.00,2.0,3.0,38.306,37.926,1.381,254.0,1216.0,-1.836,sample,36.068667,-2.298164,-2.164419,low
162,d,244.50,3.0,3.0,37.184,36.855,1.329,230.0,1101.0,-2.023,sample,34.946667,-2.511974,-2.376907,low
167,d,316.50,4.0,3.0,18.109,17.280,0.828,546.0,2611.0,-1.684,sample,15.871667,-2.712849,-2.595194,low
172,d,316.50,5.0,3.0,51.128,48.791,2.337,1608.0,7685.0,-2.067,sample,48.890667,-2.418528,-2.359389,high
177,d,397.50,5.0,3.0,57.164,54.550,2.613,1656.0,7915.0,-2.322,sample,54.926667,-2.645285,-2.588791,high
182,d,671.00,3.0,3.0,30.368,28.979,1.390,801.0,3830.0,-1.558,sample,28.130667,-2.128468,-2.024863,low
187,SW,NaN,NaN,3.0,36.826,35.110,1.716,1082.0,5280.0,19.092,standard,34.588667,19.963768,20.051890,low
192,SW,NaN,NaN,3.0,49.543,47.234,2.310,1439.0,7017.0,20.400,standard,47.305667,21.099276,21.167727,high
197,SW,NaN,NaN,3.0,37.015,35.289,1.726,1111.0,5421.0,19.897,standard,34.777667,20.815818,20.902342,low
202,SW,NaN,NaN,3.0,54.870,52.309,2.561,1644.0,8029.0,20.060,standard,52.632667,20.674049,20.731204,high
207,SW,NaN,NaN,3.0,37.398,35.656,1.742,1160.0,5651.0,19.320,standard,35.160667,20.192094,20.275918,low
212,SW,NaN,NaN,3.0,48.349,46.093,2.255,1425.0,6959.0,19.451,standard,46.111667,20.122337,20.191560,high
217,SW,NaN,NaN,3.0,37.420,35.675,1.745,1101.0,5373.0,19.377,standard,35.182667,20.252173,20.339248,low
222,SW,NaN,NaN,3.0,55.282,52.704,2.578,1510.0,7373.0,19.556,standard,53.044667,20.144022,20.208561,high

In [1647]:
# Create df with only standard data
df_standards = df_data[(df_data.Type == 'standard')] 
#Sort values by ID and area
df_standards = df_standards.sort_values(['Identifier', 'Area_All'])

df_standards

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group
27,AGS2,NaN,NaN,3.0,17.677,16.865,0.812,529.0,2537.0,2.962,standard,15.439667,2.577607,2.696199,low
37,AGS2,NaN,NaN,3.0,21.169,20.196,0.973,634.0,3045.0,1.978,standard,18.931667,1.548221,1.661027,low
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard,30.005667,2.993089,3.091956,low
47,AGS2,NaN,NaN,3.0,34.895,33.292,1.603,995.0,4779.0,1.457,standard,32.657667,1.172164,1.265079,low
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738,1.479052,low
42,AGS2,NaN,NaN,3.0,49.852,47.562,2.289,1446.0,6945.0,1.215,standard,47.614667,1.008267,1.076332,high
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892,1.567164,high
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449,1.903875,high
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554,1.662475,high
32,AGS2,NaN,NaN,3.0,67.674,64.568,3.106,2080.0,9981.0,1.387,standard,65.436667,1.242453,1.275585,high
187,SW,NaN,NaN,3.0,36.826,35.110,1.716,1082.0,5280.0,19.092,standard,34.588667,19.963768,20.051890,low
197,SW,NaN,NaN,3.0,37.015,35.289,1.726,1111.0,5421.0,19.897,standard,34.777667,20.815818,20.902342,low
207,SW,NaN,NaN,3.0,37.398,35.656,1.742,1160.0,5651.0,19.320,standard,35.160667,20.192094,20.275918,low
217,SW,NaN,NaN,3.0,37.420,35.675,1.745,1101.0,5373.0,19.377,standard,35.182667,20.252173,20.339248,low
212,SW,NaN,NaN,3.0,48.349,46.093,2.255,1425.0,6959.0,19.451,standard,46.111667,20.122337,20.191560,high
192,SW,NaN,NaN,3.0,49.543,47.234,2.310,1439.0,7017.0,20.400,standard,47.305667,21.099276,21.167727,high
202,SW,NaN,NaN,3.0,54.870,52.309,2.561,1644.0,8029.0,20.060,standard,52.632667,20.674049,20.731204,high
222,SW,NaN,NaN,3.0,55.282,52.704,2.578,1510.0,7373.0,19.556,standard,53.044667,20.144022,20.208561,high

In [1648]:
#Drop outliers in place
df_standards.drop(df_standards.index[2], inplace=True)
df_standards.drop(df_standards.index[0], inplace=True)

# Calculate the slope and intercept for calculated vs. true value of the stds

# Append true value column to the standard table
# For AGS2
df_standards.loc[df_standards['Identifier'] \
                  == 'AGS2', 'True_d34S'] = 1.89
# For SW
df_standards.loc[df_standards['Identifier'] \
                  == 'SW', 'True_d34S'] = 21
                       
# Group by Std_group
df_stdgroup = df_standards.groupby (['Std_group'])

df_standards

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,True_d34S
37,AGS2,NaN,NaN,3.0,21.169,20.196,0.973,634.0,3045.0,1.978,standard,18.931667,1.548221,1.661027,low,1.89
47,AGS2,NaN,NaN,3.0,34.895,33.292,1.603,995.0,4779.0,1.457,standard,32.657667,1.172164,1.265079,low,1.89
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738,1.479052,low,1.89
42,AGS2,NaN,NaN,3.0,49.852,47.562,2.289,1446.0,6945.0,1.215,standard,47.614667,1.008267,1.076332,high,1.89
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892,1.567164,high,1.89
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449,1.903875,high,1.89
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554,1.662475,high,1.89
32,AGS2,NaN,NaN,3.0,67.674,64.568,3.106,2080.0,9981.0,1.387,standard,65.436667,1.242453,1.275585,high,1.89
187,SW,NaN,NaN,3.0,36.826,35.110,1.716,1082.0,5280.0,19.092,standard,34.588667,19.963768,20.051890,low,21.00
197,SW,NaN,NaN,3.0,37.015,35.289,1.726,1111.0,5421.0,19.897,standard,34.777667,20.815818,20.902342,low,21.00
207,SW,NaN,NaN,3.0,37.398,35.656,1.742,1160.0,5651.0,19.320,standard,35.160667,20.192094,20.275918,low,21.00
217,SW,NaN,NaN,3.0,37.420,35.675,1.745,1101.0,5373.0,19.377,standard,35.182667,20.252173,20.339248,low,21.00
212,SW,NaN,NaN,3.0,48.349,46.093,2.255,1425.0,6959.0,19.451,standard,46.111667,20.122337,20.191560,high,21.00
192,SW,NaN,NaN,3.0,49.543,47.234,2.310,1439.0,7017.0,20.400,standard,47.305667,21.099276,21.167727,high,21.00
202,SW,NaN,NaN,3.0,54.870,52.309,2.561,1644.0,8029.0,20.060,standard,52.632667,20.674049,20.731204,high,21.00
222,SW,NaN,NaN,3.0,55.282,52.704,2.578,1510.0,7373.0,19.556,standard,53.044667,20.144022,20.208561,high,21.00

Below, we make a linear regression for the standards of each area group.

In [1649]:
# Get the slope and intercept for the standards of each group
# Define column names
names = ['Std_group', 'R squared', 'Intercept', 'Slope']

# Initialize empty dataframe to save fit results
df_linreg_stds = pd.DataFrame(columns=names)
                 
# Create variables for linear regression
#Loop through standard groups                       
for group, data in enumerate (df_stdgroup):
    #x will be the values of d34S of the stds corrected by blanks and linearity
    x_std = data[1].Correction_of_d34S_by_amplitude.values.reshape((-1,1))
    #y will be the true values of d34S of each standard
    y_std = data[1].True_d34S
    # Create model
    model = LinearRegression().fit(x_std,y_std)
    #Determine R square, intercept and slope
    r_sq_stds = model.score(x_std,y_std)
    intercept_stds = model.intercept_
    s1 = model.coef_
    slope_stds = s1[0]
    # Store parameters and group as list
    params = (data[1].Std_group.unique(), r_sq_stds, intercept_stds, slope_stds)
 
    # Convert list to pandas Series
    series = pd.Series(params, index=names)   
    # Append parameters to dataframe
    df_linreg_stds = df_linreg_stds.append(series, ignore_index=True)
#Round the values of the dataframe to two decimal places
df_linreg_stds = df_linreg_stds.round(2)     
df_linreg_stds

  Std_group  R squared  Intercept  Slope
0    [high]        1.0       0.40   1.00
1     [low]        1.0       0.42   1.01

Finally, let's apply the standard correction to the samples based on their area:

In [1650]:
#Apply corrections by true value and area

# Initialize lists to save values
slopes = []
intercepts = []
Correction_of_d34S_by_true_value = []

#loop through rows in dataframe
for index, row in df_data.iterrows():
    # Extract standard group
    Std_group = row.Std_group
    # Extract slope and intercept
    slope = df_linreg_stds[df_linreg_stds.Std_group == Std_group].Slope.iloc[0]
    intercept = df_linreg_stds[df_linreg_stds.Std_group == Std_group].Intercept.iloc[0]
    slopes.append(slope)
    intercepts.append(intercept)
    # Compute corrected concentration
    Correction_of_d34S_by_true_value.append(intercept + slope * row.Correction_of_d34S_by_amplitude)
    
# Append values to dataframe
df_data['Correction_of_d34S_by_true_value'] = Correction_of_d34S_by_true_value

df_data.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,Correction_of_d34S_by_true_value
2,AGS2,NaN,NaN,3.0,42.040,40.112,1.928,1260.0,6046.0,1.625,standard,39.802667,1.400738,1.479052,low,1.913843
7,AGS2,NaN,NaN,3.0,58.231,55.559,2.672,1748.0,8385.0,1.997,standard,55.993667,1.852449,1.903875,high,2.303875
12,AGS2,NaN,NaN,3.0,50.504,48.187,2.317,1533.0,7355.0,1.686,standard,48.266667,1.503892,1.567164,high,1.967164
17,AGS2,NaN,NaN,3.0,61.173,58.364,2.809,1739.0,8351.0,1.757,standard,58.935667,1.610554,1.662475,high,2.062475
22,AGS2,NaN,NaN,3.0,32.243,30.761,1.483,887.0,4258.0,3.175,standard,30.005667,2.993089,3.091956,low,3.542875

Since all the corrections have been done, we will now export the corrected data, which must be combined with the quantification data to get the plots of sulfide degradation and change in the $\delta^{34}S$ of the remaining sulfide as a function of time or -ln of sulfide remaining.

In [1651]:
# Create dataframe that includes only data from the samples
df_samples = df_data[(df_data.Type == 'sample')]

# Export data table
df_samples.to_csv('/Users/daniosro/git/MSO/ctep_wt/data/processed/EA/20210427_EA.csv')
df_samples.head()

,Identifier,Time_h,Replicate,Peak_Nr,Area_All,Area_64,Area_66,Ampl_64,Ampl_66,d34S,Type,Correction_of_area_blank,Correction_of_d34S_blank,Correction_of_d34S_by_amplitude,Std_group,Correction_of_d34S_by_true_value
52,b,52.5,7.0,3.0,32.441,31.328,1.112,74.0,355.0,-1.356,sample,30.203667,-1.872351,-1.728689,low,-1.325976
57,b,61.5,4.0,3.0,19.228,18.349,1.880,551.0,2635.0,-1.166,sample,16.990667,-2.058879,-1.941499,low,-1.540914
62,b,61.5,5.0,3.0,30.804,29.389,1.415,949.0,4535.0,-1.123,sample,28.566667,-1.650692,-1.555242,low,-1.150795
67,b,69.0,7.0,3.0,29.659,28.301,1.357,927.0,4429.0,-1.046,sample,27.421667,-1.589444,-1.492781,low,-1.087709
72,b,148.5,5.0,3.0,24.879,23.741,1.139,768.0,3671.0,-1.674,sample,22.641667,-2.394229,-2.288806,low,-1.891694

### Analytical repeatability of measurements

Let's calculate the analytical repeatability of the EA-IRMS measurements.

In [1652]:
# Update standard df
# Create a dataframe for only standards from the updated data dataframe
df_standards = df_data[(df_data.Type == 'standard')]

#Drop outliers in place
df_standards.drop(df_standards.index[5], inplace=True)
df_standards.drop(df_standards.index[4], inplace=True)
#Sort values
df_standards = df_standards.sort_values(['Identifier', 'Area_All'])

#Group standards by identifier and area
grouped_standards = df_standards.groupby(['Identifier', 'Std_group'])

# Determine the mean of each standard  and rename the series
mean_stds = grouped_standards['Correction_of_d34S_by_true_value'].mean()
mean_stds = mean_stds.rename("d34S_mean")

# Determine the standard deviation of each standard  and rename the series
std_dev_stds = grouped_standards['Correction_of_d34S_by_true_value'].std()
std_dev_stds = std_dev_stds.rename("d34S_stdev")

#Pass series to individual dataframes
df_mean_stds=mean_stds.to_frame()
df_std_dev_stds=std_dev_stds.to_frame()

In [1653]:
#merge the mean and standard deviation dataframes
df_anrep = pd.merge(df_mean_stds, df_std_dev_stds,  how='outer', on=['Identifier', 'Std_group'])

#Reset index of the dataframe
df_anrep = df_anrep.reset_index()

#Add column of true value of the standards
df_anrep.loc[df_anrep['Identifier'] \
                  == 'AGS2', 'True_d34S'] = 1.89
df_anrep.loc[df_anrep['Identifier'] \
                  == 'SW', 'True_d34S'] = 21

#Determine the accuracy by subtracting the true value from the average value of each standard
df_anrep ['Accuracy'] = abs(df_anrep ['True_d34S'] - df_anrep ['d34S_mean'])
df_anrep

  Identifier Std_group  d34S_mean  d34S_stdev  True_d34S  Accuracy
0       AGS2      high   1.897086    0.325514       1.89  0.007086
1       AGS2       low   1.903070    0.200171       1.89  0.013070
2         SW      high  20.974763    0.467985      21.00  0.025237
3         SW       low  21.016273    0.365271      21.00  0.016273

## Import the quantification data and calculate the fraction of sulfate produced

Let's begin by loading the sulfate quantification data (ion chromatography):

In [1654]:
# Import table with data
df_ics =  pd.read_csv ('/Users/daniosro/git/MSO/ctep_wt/data/raw/ICS/20210423_ICS.csv')

df_ics.head()

  treatment      type  replicate  time_h   Amount  corrected_conc_dil
0        A1  standard        NaN     NaN  10.2593                 NaN
1        A2  standard        NaN     NaN  20.3637                 NaN
2        A3  standard        NaN     NaN  42.8230                 NaN
3        A4  standard        NaN     NaN  61.7583                 NaN
4        A5  standard        NaN     NaN  83.2282                 NaN

The only correction made was by the dilution factor. The machine software calculated the concentration in each sample vial based on the standards.

In [1655]:
# Filter by sample only
df_samples_ics = df_ics[(df_ics.type == 'sample')]
df_samples_ics.head()

   treatment    type  replicate  time_h   Amount  corrected_conc_dil
7          b  sample        4.0    61.5  48.1400          802.333333
8          b  sample        5.0    61.5  40.6344          677.240000
10         b  sample        5.0   148.5  38.1748         1590.616667
11         d  sample        4.0   316.5  29.4517         1732.452941
12         d  sample        5.0   316.5  30.8041         1812.005882

We will calculate the fraction of reactant remaining for each replicate at each time point:

In [1656]:
#Create ID column with the combination of treatment, time and replicate
df_samples_ics['ID'] = df_samples_ics['treatment'] + '_' +\
df_samples_ics['time_h'].astype(int).map(str) + '_' + \
df_samples_ics['replicate'].map(str)

# Get the max values for concentration for each treatment and replicate and 
# append it to a new column
df_samples_ics['max_conc'] = \
df_samples_ics.groupby(['treatment'])['corrected_conc_dil'].transform(max)

# Get the fraction of reactant remaining for each time point
df_samples_ics['f_R'] = 1-(abs(np.divide(df_samples_ics['corrected_conc_dil'], \
               df_samples_ics['max_conc'])))

# Remove duplicates
df_samples_ics = df_samples_ics.drop_duplicates(subset ="ID")

df_samples_ics.head()

,treatment,type,replicate,time_h,Amount,corrected_conc_dil,ID,max_conc,f_R
7,b,sample,4.0,61.50,48.1400,802.333333,b_61_4.0,1892.213333,0.575982
8,b,sample,5.0,61.50,40.6344,677.240000,b_61_5.0,1892.213333,0.642091
10,b,sample,5.0,148.50,38.1748,1590.616667,b_148_5.0,1892.213333,0.159388
11,d,sample,4.0,316.50,29.4517,1732.452941,d_316_4.0,1895.300000,0.085922
12,d,sample,5.0,316.50,30.8041,1812.005882,d_316_5.0,1895.300000,0.043948
13,b,sample,6.0,316.50,30.8115,1812.441176,b_316_6.0,1892.213333,0.042158
14,b,sample,4.0,397.50,25.5825,1705.500000,b_397_4.0,1892.213333,0.098675
16,d,sample,5.0,397.50,28.4295,1895.300000,d_397_5.0,1895.300000,0.000000
17,b,sample,6.0,397.50,28.3832,1892.213333,b_397_6.0,1892.213333,0.000000
18,b,sample,7.0,52.50,9.0530,150.883333,b_52_7.0,1892.213333,0.920261
19,b,sample,7.0,69.00,15.6193,390.482500,b_69_7.0,1892.213333,0.793637
20,b,sample,8.0,92.50,31.4015,1046.716667,b_92_8.0,1892.213333,0.446829
21,b,sample,9.0,92.50,31.7186,1057.286667,b_92_9.0,1892.213333,0.441243
22,b,sample,8.0,163.50,28.3757,1182.320833,b_163_8.0,1892.213333,0.375165
23,b,sample,9.0,163.50,27.3253,1138.554167,b_163_9.0,1892.213333,0.398295
24,b,sample,8.0,188.00,25.1042,1255.210000,b_188_8.0,1892.213333,0.336645
25,b,sample,9.0,216.00,21.2620,1250.705882,b_216_9.0,1892.213333,0.339025
27,b,sample,9.0,244.50,19.2828,1285.520000,b_244_9.0,1892.213333,0.320626
28,b,sample,9.0,671.00,18.9002,1453.861538,b_671_9.0,1892.213333,0.231661
29,d,sample,1.0,76.00,30.4577,507.628333,d_76_1.0,1895.300000,0.732165
30,d,sample,1.0,92.75,30.3291,758.227500,d_92_1.0,1895.300000,0.599943
31,d,sample,2.0,92.75,29.9811,749.527500,d_92_2.0,1895.300000,0.604534
32,d,sample,1.0,163.50,32.5405,1084.683333,d_163_1.0,1895.300000,0.427698
33,d,sample,2.0,163.50,29.4579,981.930000,d_163_2.0,1895.300000,0.481913
34,d,sample,2.0,188.00,25.2452,1051.883333,d_188_2.0,1895.300000,0.445004
35,d,sample,3.0,188.00,29.5567,1231.529167,d_188_3.0,1895.300000,0.350219
36,d,sample,2.0,216.00,22.4173,1120.865000,d_216_2.0,1895.300000,0.408608
37,d,sample,3.0,244.50,23.7812,1398.894118,d_244_3.0,1895.300000,0.261914
38,d,sample,3.0,671.00,22.8303,1522.020000,d_671_3.0,1895.300000,0.196950

In [1657]:
# Export data table
df_samples_ics.to_csv(f'{homedir}/ctep_wt/data/processed/ICS/20210423_ICS.csv')

## Create master table

Now, let's create a table to compile the corrected values from EA-IRMS and quantification of sulfide by ion chromatography. We will begin by loading the processed EA data and dropping the non-needed columns:

In [1658]:
# Import tables with the EA processed data
df_ea_1 = pd.read_csv(f'{homedir}/ctep_wt/data/processed/EA/20210427_EA.csv')

# Create empty master dataframe
df_master=pd.DataFrame()

# Fill master table
df_master['treatment'] = df_ea_1['Identifier']
df_master['d34S_corrected'] = df_ea_1['Correction_of_d34S_by_true_value']
df_master['replicate'] = df_ea_1['Replicate']
df_master['time_h'] = (df_ea_1['Time_h']).astype(int)

#Create new ID column with the combination of enzyme, time and date
df_master['ID'] = df_master['treatment'] + '_' +\
df_master['time_h'].map(str) + '_' + df_master['replicate'].map(str)

# Sort values
df_master = df_master.sort_values(['treatment', 'time_h', 'ID'])
df_master.head()

  treatment  d34S_corrected  replicate  time_h         ID
0         b       -1.325976        7.0      52   b_52_7.0
1         b       -1.540914        4.0      61   b_61_4.0
2         b       -1.150795        5.0      61   b_61_5.0
3         b       -1.087709        7.0      69   b_69_7.0
4         b       -1.891694        5.0     148  b_148_5.0

Now, we will fuse this table with the quantification by ion chromatography table:

In [1659]:
# Append f_r (fraction of reactant remaining) column to the master table               
df_master = df_master.merge(df_samples_ics.filter(['ID','f_R']), how='left',
                 left_on='ID', right_on='ID') 
# Append sulfate concentration column to the master table  
df_master = df_master.merge(df_samples_ics.filter(['ID', 'corrected_conc_dil']), \
                            how='left', left_on='ID', right_on='ID')  

#Substitute zeroes by a very small non-zero value in the 1-f_R column to be able to calculate
#the reg line
df_master['f_R'] = df_master['f_R'].replace(0, 0.0001)

df_master.head()

  treatment  d34S_corrected  replicate  time_h         ID       f_R
0         b       -1.325976        7.0      52   b_52_7.0  0.920261
1         b       -1.540914        4.0      61   b_61_4.0  0.575982
2         b       -1.150795        5.0      61   b_61_5.0  0.642091
3         b       -1.087709        7.0      69   b_69_7.0  0.793637
4         b       -1.891694        5.0     148  b_148_5.0  0.159388

To determine the fractionation factor $^{34}\varepsilon$, we will use a linearized form of the Rayleigh distillation equation (Mariotti et al., 1981; Scott et al., 2014):

$$
ln (^{34}\delta{(SO_4^{-2})} +1) = ln (^{34}\delta{(S^{-2})_0} +1) + {^{34}\varepsilon} \cdot (f \cdot ln f)/(1-f),
$$ 

where $^{34}\delta{(SO_4^{-2})}$ is the delta value for 34/32 S for the produced sulfate at any given point, $^{34}\delta{(S^{-2})_0}$ is the delta value for 34/32 S for sulfide at t = 0, ${^{34}\varepsilon}$ is the fractionation factor of 34/32 S in the oxidation reaction from elemental sulfur to sulfate and f is the fraction of reactant (elemental sulfur or sulfide) remaining at the point where $^{34}\delta{(SO_4^{-2}})$ is measured. We will append a column corresponding to $ln (^{34}\delta{(SO_4^{-2}}) +1)$ to the dataframe.

In [1661]:
# Append f_r.ln(f_r)/(1-f_r) column to the master table
oneminus_f_r = 1-df_master['f_R']
df_master['xaxis_linreg'] = ((np.log(df_master['f_R']))*df_master['f_R'])/oneminus_f_r

()#Calculate the ln (delta_sulfate+1) and append to dataframe
df_master['d34S_sulfate'] = 1000*np.log(df_master['d34S_corrected']/1000+1)

#Show dataframe
df_master.head()

,treatment,d34S_corrected,replicate,time_h,ID,f_R,corrected_conc_dil,xaxis_linreg,d34S_sulfate
0,b,-1.325976,7.0,52,b_52_7.0,0.920261,150.883333,-0.959026,-1.326856
1,b,-1.540914,4.0,61,b_61_4.0,0.575982,802.333333,-0.749395,-1.542103
2,b,-1.150795,5.0,61,b_61_5.0,0.642091,677.240000,-0.794790,-1.151457
3,b,-1.087709,7.0,69,b_69_7.0,0.793637,390.482500,-0.888883,-1.088301
4,b,-1.891694,5.0,148,b_148_5.0,0.159388,1590.616667,-0.348202,-1.893485
5,b,-1.449384,8.0,163,b_163_8.0,0.375165,1182.320833,-0.588648,-1.450435
6,b,-1.881558,9.0,163,b_163_9.0,0.398295,1138.554167,-0.609361,-1.883330
7,b,-1.545263,8.0,188,b_188_8.0,0.336645,1255.210000,-0.552516,-1.546459
8,b,-1.660082,9.0,216,b_216_9.0,0.339025,1250.705882,-0.554812,-1.661461
9,b,-1.998949,9.0,244,b_244_9.0,0.320626,1285.520000,-0.536826,-2.000950
10,b,-1.961381,6.0,316,b_316_6.0,0.042158,1812.441176,-0.139362,-1.963307
11,b,-1.985105,4.0,397,b_397_4.0,0.098675,1705.500000,-0.253541,-1.987078
12,b,-2.531133,6.0,397,b_397_6.0,0.000100,1892.213333,-0.000921,-2.534342
13,b,-1.668983,9.0,671,b_671_9.0,0.231661,1453.861538,-0.440951,-1.670377
14,d,-1.287933,1.0,76,d_76_1.0,0.732165,507.628333,-0.852211,-1.288763
15,d,-1.154308,1.0,92,d_92_1.0,0.599943,758.227500,-0.766199,-1.154975
16,d,-1.127605,2.0,92,d_92_2.0,0.604534,749.527500,-0.769371,-1.128242
17,d,-1.253690,1.0,163,d_163_1.0,0.427698,1084.683333,-0.634735,-1.254476
18,d,-1.313476,2.0,163,d_163_2.0,0.481913,981.930000,-0.679022,-1.314339
19,d,-1.461897,2.0,188,d_188_2.0,0.445004,1051.883333,-0.649207,-1.462966
20,d,-1.382576,3.0,188,d_188_3.0,0.350219,1231.529167,-0.565496,-1.383533
21,d,-1.766063,2.0,216,d_216_2.0,0.408608,1120.865000,-0.618378,-1.767625
22,d,-1.980676,3.0,244,d_244_3.0,0.261914,1398.894118,-0.475414,-1.982640
23,d,-2.201146,4.0,316,d_316_4.0,0.085922,1732.452941,-0.230701,-2.203572
24,d,-1.959389,5.0,316,d_316_5.0,0.043948,1812.005882,-0.143638,-1.961311
25,d,-2.188791,5.0,397,d_397_5.0,0.000100,1895.300000,-0.000921,-2.191189
26,d,-1.625112,3.0,671,d_671_3.0,0.196950,1522.020000,-0.398488,-1.626434

Now, we can export the master table, with the corrected data from both Cline assay (quantification) and EA-IRMS for each enzyme.

In [1662]:
# Export master table with the data with all corrections

df_master.to_csv(f'{homedir}/ctep_wt/data/processed/EA_cline/20210427_EA_ICS.csv')

# Calculate $\epsilon$

In [1663]:
# Get the slope and intercept for each treatment

df_linreg = df_master.groupby(['treatment']).apply(
        lambda g: (((LinearRegression().fit((g.xaxis_linreg.values).\
                                      reshape((-1,1)), g.d34S_sulfate.values)\
.coef_[0], LinearRegression().fit((g.xaxis_linreg.values).reshape((-1,1)), \
                         g.d34S_sulfate.values).intercept_, LinearRegression().\
                     fit((g.xaxis_linreg.values).reshape((-1,1)), g.d34S_sulfate.values).\
                     score((g.xaxis_linreg.values).reshape((-1,1)), g.d34S_sulfate.values)\
                         )))).apply(pd.Series)\
.rename(columns={0:'slope', 1:'intercept', 2: 'R_squared'}).reset_index()

# Assign name as the index column
#df_100 =df_100.round(2)
df_linreg

  treatment     slope  intercept  R_squared
0         b -1.228055  -2.343480   0.772621
1         d -1.311478  -2.278219   0.774111

# Plot of the isotope data

In [1668]:
# Group by treatment
df_group = df_master.groupby(['treatment'])

# Define colors
colors = ['#0072B2', '#009E73']

# Define markers
markers = ['.','d']

# Define fig and axes
fig = plt.figure(figsize=(2.95, 1.95), dpi=192)
ax = fig.add_subplot(111)

# Loop through replicates
for i, (group, data) in enumerate(df_group):
    #Calculate trendline  
    z = np.polyfit(data.xaxis_linreg, data.d34S_sulfate, 1)
    p = np.poly1d(z)
 
    # Plot fit
    ax.plot(data.xaxis_linreg, p(data.xaxis_linreg), c=colors[i])
    
    # Plot experimental data
    ax.scatter(data.xaxis_linreg, data.d34S_sulfate, color=colors[i], marker=markers[i],
              label = group)
    #ax.set_title('DddY')
    ax.set_xlabel('$f_{R}.ln (f_{R})/(1-f_{R})$')
    ax.set_ylabel('ln ($\delta{}^{34}S_{VCDT}$+1) (‰)')
    ax.set_ylim(-3,-1,1)

#Show legend
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

#Save figure
fig.savefig(f'{homedir}/ctep_wt/figures/ctepwt_fr_sulfate.pdf', bbox_inches='tight')

Notes:
-The control must be repeated and in triplicates, with newly autoclaved media. these values must be substituted as the 0 for one of the bs and d.
-Temporarily, a0 was relabelled as d0 and c0 for the EA measurements.